version: "3.2"
services:
 redis:
    image: "redis:alpine"
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./.ops/redis:/var/lib/redis
      - ./ops/redis.conf:/usr/local/etc/redis/redis.conf
      - ./ops/tls:/data/tls
    ports:
      - "6379:6379"
    environment:
      - REDIS_REPLICATION_MODE=master
 app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./ops/tls:/app/ops/tls
    command: python app
    environment:
      REDIS_HOST: redis
    depends_on:
      - redis